### ISSUE TITLE
cookie size of 4kb exceeded! try ChromePhp::useFile() to pull the log data from disk

### ISSUE THREAD

**Issue by samiujan** [ccampbell/chromephp#11]
Got this error when following the steps given here: http://www.chromephp.com/

Using Google Chrome 16.0.912.63 m on Window 7 and the latest version (version 2.2.3) of ChromePHP

Error: cookie size of 4kb exceeded! try ChromePhp::useFile() to pull the log data from disk

This is the code:

```
require '../src/ChromePhp.php';
ChromePhp::log('hello world');
ChromePhp::log($_SERVER);
```

Error occurs on the last line

**Comment by ccampbell** [comment]
This is a known issue in the current release.  It is documented here www.chromephp.com/#file_storage

There are two options.  You can use the current version of the extension with ChromePhp::useFile() to log the data to disk as described on that page or you can use the new experimental version of the extension which uses the chrome webrequest api and bypasses cookies completely.

If you want to try the experimental version you will have to:
1.  Download the new server side class at https://github.com/ccampbell/chromephp/blob/webrequest-api/ChromePhp.php
2.  Go to about:flags in your browser and turn on experimental extension apis
3.  Uninstall the existing extension from your browser
4.  Install the experimental version by going to http://chromephp.com/chromephp-extension.crx

The WebRequest API will no longer be experimental when Chrome 17 is released so at that point I will update the actual extension/libraries to use that.
