### ISSUE TITLE
Can I do this?

### ISSUE THREAD

**Issue by mpmont** [ccampbell/chromephp#17]
Can i fork your project and turn this into a helper for codeigniter and release it as a spark?

With your licence and copyright obviously.

cheers,
Marco

**Comment by ccampbell** [comment]
You just have to make sure that whatever license you are using is compatible with the Apache 2 license and that you include the original license/copyright info.

Other than that I don't see why not!

**Comment by mpmont** [comment]
ok, will do! Thanks...
