### ISSUE TITLE
Calling groupEnd without any parameters fails silently.

### ISSUE THREAD

**Issue by davidsev** [ccampbell/chromephp#2]
Example:
    ChromePhp::groupCollapsed('My test group');
    ChromePhp::log('test log');
    ChromePhp::error('test error');
    ChromePhp::groupEnd();
    ChromePhp::error('test error 2');

The expected behaviour is that a group gets logged with two items in it, followed by an error.
In practice the call to groupEnd is ignored as it has no arguments, and so all three items go into the group.

As a work around I can call ChromePhp::groupEnd(''), however this is non-obvious and non-intuitive.

**Comment by ccampbell** [comment]
trigger groupEnd even if nothing is passed in closed by c6ae96226e5c2e01c800993550c3c39271ce3597
