### ISSUE TITLE
Unable to install chromephp extension - An error has occurred, Download was not a CRX

### ISSUE THREAD

**Issue by ajohnstone** [ccampbell/chromephp#24]
Unable to install chromephp extension, states...

"An error has occurred, Download was not a CRX"

![Screen Shot 2013-01-19 at 01 08 22](https://f.cloud.github.com/assets/173567/79902/c5604f20-61d4-11e2-8559-b2689f6b26be.png)

**Comment by ccampbell** [comment]
I just tried uninstalling and reinstalling and it worked fine for me on OS X in Chrome `24.0.1312.52`.  If you try again does it work? What operating system/version are you using?

**Comment by ajohnstone** [comment]
Thanks for the quick response, I tried to install several times and kept producing the error above last night.
I've just tried again and it works correctly now, I am using **24.0.1312.52**. Seems like an issue with the chrome store. Not sure if you tried re-uploading to the store again, however seems to be resolved now.
