### ISSUE TITLE
Installation problem on latest Chrome

### ISSUE THREAD

**Issue by rock-weld** [ccampbell/chromephp#27]
Each time I try to install chromephp I get an error telling me 'Download was not a CRX'.
When I try to install it manually I am told 'CRX_MAGIC_NUMBER_INVALID'.
I get the crx from my Downloads directory.
I am running Mountain Lion with Chrome version: 24.0.1312.56
Thanks

**Comment by rock-weld** [comment]
Solved.
After a bit more searching it seems that you need to be signed into Chrome.
As soon as I did that, no problems

**Comment by ccampbell** [comment]
Do you know if this a problem with all extensions or just ChromePHP?

**Comment by rock-weld** [comment]
It seems to be a problem with all extensions not just yours although I haven't tested that. I found the solution when I assumed it was a Chrome problem and searched in that context
