### ISSUE TITLE
wp-ChromeLogger (WordPress Wrapper)

### ISSUE THREAD

**Issue by daslicht** [ccampbell/chromephp#37]
Hello, 
I have just created a simpel WordPress MU-Plugin which wraps ChomePHP so that it can be used globally.
see: https://github.com/daslicht/wp-ChromeLogger

I just copied your ChromePHP.php to my lib folder, is there any smarter way to include it, especially regarding upcoming updates it?  
composer?

Best Regards Marc

**Comment by ccampbell** [comment]
It should be available in composer.

https://packagist.org/packages/ccampbell/chromephp
