### ISSUE TITLE
Example for ChromePhp::table()

### ISSUE THREAD

**Issue by Svish** [ccampbell/chromephp#59]
Could you add an example of how to use the `table` type? Not really understanding how to use it properly... like... what do I pass in there? 🤔

Tried looking in the [techspecs](https://craig.is/writing/chrome-logger/techspecs) and in [`ChromePhp.php`](https://github.com/ccampbell/chromephp/blob/master/ChromePhp.php), but yeah... not feeling any wiser 😕

**Comment by marqusG** [comment]
I have just got a solution. You have to pass an array of array: each child array is a row in the table and each value in the child array is a column. A column with index is automatically added in the log.
So the following call:
`include 'ChromePhp.php';
$p1 = array(
  array('John', 'Wayne', 'M'),
  array('Gena', 'Rowllands', 'F'),
  array('Clark', 'Gable', 'M')
);
ChromePhp::table($p1);
`
gives you the following result
![screenshot - 07_19_17 20_06_03](https://user-images.githubusercontent.com/1384264/28384767-c4bdfae2-6cbd-11e7-9e25-122771d34113.jpg)

**Comment by Svish** [comment]
Thanks, that made sense, and worked. 🎉
Seems it also works to use assoc arrays for providing column and/or row titles. 👍
