### ISSUE TITLE
Fatal error: Maximum function nesting level of '100' reached, aborting! 

### ISSUE THREAD

**Issue by sudo-tee** [ccampbell/chromephp#7]
When working with objects that have some sort of circular references to each other I have this issue

Sample of the stack trace

ChromePhp::log( )   ../ConsoleLogger.php:54
4   0.0420  223068  ChromePhp::_log( )  ../ChromePhp.php:183
5   0.0420  224548  ChromePhp->_convert( )  ../ChromePhp.php:272
6   0.0421  226376  ChromePhp->_convert( )  ../ChromePhp.php:311
7   0.0421  228332  ChromePhp->_convert( )  ../ChromePhp.php:311
8   0.0421  230236  ChromePhp->_convert( )  ../ChromePhp.php:311
..... until I reach the error

**Comment by ccampbell** [comment]
fixed in https://github.com/ccampbell/chromephp/pull/8
