### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by peter279k** [ccampbell/chromephp#71]
As title, is this project still active?

They've many issues and pull requests to be concerned and reviewed.

**Comment by hopeseekr** [comment]
Over 4 years ago, I found this project abandoned. I forked https://github.com/phpexpertsinc/chromephp and edited it per my concerns.

If you want, you can port PRs over there and I'm more than happy to take over.

**Comment by peter279k** [comment]
Thanks, @hopeseekr :).

**Comment by peter279k** [comment]
To @ccampbell, if possible, please add some unmaintained notification message in `README` on this repo.

I also suggest adding the "Transferring to [phpexpertsinc/chromephp](https://github.com/phpexpertsinc/chromephp)" message in `README`.

**Comment by hopeseekr** [comment]
Heads up, I myself abandoned my own fork fo this project some 5 years ago :-/
